dist: trusty
conditions: v1

language: node_js
addons:
  chrome: stable

env:
- ASCIIDOCTOR_CORE_VERSION=v2.0.10
- ASCIIDOCTOR_CORE_VERSION=master

node_js:
- 'lts/*'
- 'node'

jdk:
- oraclejdk8

install:
- npm ci
- npm ci --prefix packages/asciidoctor
- npm ci --prefix packages/core

cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.dts"

script:
- npm run lint
- npm run test
- npm run test --prefix packages/asciidoctor
- npm run travis --prefix packages/core
